"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def register_attack_family(name: str, template: str, rationale: str) -> str:
    """Register a reviewed attack family. Requires human approval (policy).

    Args:
        name: Id like 'A6_markdown_quote'.
        template: Approved template.
        rationale: Why this family tests the hypothesis.
    """
    return tools_impl.register_attack_family(name, template, rationale)
