"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def review_attack_proposal(name: str, template: str) -> str:
    """Safety review of a proposed new attack family template (static checks).

    Args:
        name: Proposed id like 'A6_markdown_quote'.
        template: Wrapping text with exactly one slot: {INSTR_EN}, {INSTR_DE} or {INSTR_B64}.
    """
    return tools_impl.review_attack_proposal(name, template)
