"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def estimate_test_value(stack: str, attack: str, n: int) -> str:
    """Estimate expected learning per sample for running n more samples of one experiment cell.

    Args:
        stack: Defense stack, e.g. 'D1+D3' or 'none'.
        attack: Attack family id, e.g. 'A4_german'.
        n: Total samples you would have for this cell after the test (1-12).
    """
    return tools_impl.estimate_test_value(stack, attack, n)
