"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def list_space() -> str:
    """List the defenses, approved attack families, limits and the study target.
    """
    return tools_impl.list_space()
