"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def record_conclusion(stack: str, attack: str, summary: str) -> str:
    """Record the lab's final answer: the stacked-defense x attack cell with the biggest gap.

    Args:
        stack: The weakest stacked defense, e.g. 'D1+D3'.
        attack: The attack family that best bypasses it.
        summary: 3-5 sentences: answer, evidence, uncertainty, next experiment.
    """
    return tools_impl.record_conclusion(stack, attack, summary)
