"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def search_literature(query: str, k: int) -> str:
    """Search scholarly literature (OpenAlex) and return titles, years, DOIs and abstract starts.

    Args:
        query: Search query, e.g. 'multilingual prompt injection detection'.
        k: Number of papers, 1-10.
    """
    return tools_impl.search_literature(query, k)
