"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def lab_status() -> str:
    """Show the sample budget used and left for this study.
    """
    return tools_impl.lab_status()
