"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def log_entry(kind: str, content: str) -> str:
    """Append an entry to the shared research log.

    Args:
        kind: One of: question, literature, hypothesis, plan, safety, result, analysis, decision, conclusion, note.
        content: Short text (max ~5 sentences) with the evidence or decision.
    """
    return tools_impl.log_entry("analyst", kind, content)
