"""Omnigent tool wrapper (generated by scripts/gen_tool_wrappers.py)."""

from omnigent_client.tools import tool

from injlab import tools_impl


@tool
def read_log(last: int) -> str:
    """Read the most recent entries of the shared research log.

    Args:
        last: How many recent entries to return, e.g. 15.
    """
    return tools_impl.read_log(last)
